
services:
  www:
    build: .
    volumes:
      - "./app:/var/www/html"
    ports:
      - 80:80
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=restaurant_app
      - MYSQL_USER=restaurant_app
      - MYSQL_PASSWORD=12345678
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes: 
  db_data: